name: dart_console
version: 4.0.2
homepage: https://github.com/onepub-dev/dart_console
description: A helper library for command-line applications that need more control over input/output than the standard library provides.
environment:
  sdk: '>=3.3.0 <4.5.0'
dependencies:
  ffi: ^2.1.2
  win32: ^5.5.1
  intl: ^0.19.0
  characters: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
platforms:
  linux:
  macos:
  windows:
